### ISSUE TITLE
music page javascript

### ISSUE THREAD

**Issue by MakenHubbard** [nss-evening-cohort-7/bandz-teamtwerk#11]
# Story:
As a developer, in order to display the data, I need to create a for loop

# Acceptance Criteria:
When the page is uploaded the user needs to see the album covers
Then the album name and year displayed below the cover
And when the user clicks on the album the songs in that album will display

# Technical Notes:
-Create a for loop to run through an object containing the album/songs data
-Add the code for an event listener for when the album is clicked it will flip to display the songs
-Display the the individual album covers side by side when in full screen and then when page size is reduced display them in a single column

**Comment by AmandaM04** [comment]
![band site - music pg](https://user-images.githubusercontent.com/36489047/37376652-4f8caf7a-26f3-11e8-90c8-a66a340b5e91.jpg)
