### ISSUE TITLE
Twitter content for homepage

### ISSUE THREAD

**Issue by briankw23** [nss-evening-cohort-7/bandz-teamtwerk#14]
# Story
As a user, in order to view the twitter, I need to insert the data into the homepage.

# Acceptance Criteria
When user comes to website
Then they should see a twitter feed card
and a photo of the tweeter
and likes and timestamp.

# Technical Notes
Loop through twitter variable and insert into the DOM on the homepage

**Comment by AmandaM04** [comment]
![band site - home pg](https://user-images.githubusercontent.com/36489047/37376616-fc7bfd4a-26f2-11e8-8b14-ba447722afcf.jpg)

**Comment by AmandaM04** [comment]
<img width="374" alt="screen shot 2018-03-13 at 7 20 28 pm" src="https://user-images.githubusercontent.com/36489047/37376731-ba60efd2-26f3-11e8-9b03-aa7909f95637.png">
