### ISSUE TITLE
Members Content JS

### ISSUE THREAD

**Issue by briankw23** [nss-evening-cohort-7/bandz-teamtwerk#18]
# Story
As a user, in order to view the member's page, I need to insert the data into the member's page.

# Acceptance Criteria
When user comes to website
Then they should see a profiles card
and a photo of the member.

# Technical Notes
Loop through member's variable and insert into the DOM on the member's page

**Comment by AmandaM04** [comment]
![band site - members](https://user-images.githubusercontent.com/36489047/37376666-643f9d2e-26f3-11e8-99c3-72809392b17c.jpg)
