### ISSUE TITLE
Nav Bar and Footer

### ISSUE THREAD

**Issue by briankw23** [nss-evening-cohort-7/bandz-teamtwerk#3]
#Story 
As a user, in order to navigate the pages within the websites and view social media sites view footer, i need to create links. 

#Acceptance Criteria
When user comes to website
Then they should see a nav bar and footer
and the links on the nav bar and footer work
and the nav bar and footer is visible on all pages of the site.

Technical Notes
create index.html
Links to pages tabs and social media icons
and copyright for the footer

**Comment by AmandaM04** [comment]
![band site - home pg](https://user-images.githubusercontent.com/36489047/37318982-20e21326-263b-11e8-9969-b720719d14bc.jpg)
