### ISSUE TITLE
Twitter Card Object

### ISSUE THREAD

**Issue by briankw23** [nss-evening-cohort-7/bandz-teamtwerk#4]
# Story
In order to display twitter information on the homepage, we need to create an object that contains the twitter card information.

# Acceptance criteria
When developer views the js file,
then we need to see the object array of twitter
and its contents

# technical Notes
create js file
var twitter =
[name_tweeter, account, message, date, # of likes, likers];

**Comment by AmandaM04** [comment]
<img width="374" alt="screen shot 2018-03-13 at 7 20 28 pm" src="https://user-images.githubusercontent.com/36489047/37376722-b333522c-26f3-11e8-9b67-c0e8efefaa8a.png">
