### ISSUE TITLE
Music Page

### ISSUE THREAD

**Issue by MakenHubbard** [nss-evening-cohort-7/bandz-teamtwerk#9]
# Story
As a user, I will be able to see all albums the band has available. I will also be able to see the songs that on those albums

# Acceptance
When user navigates to the Music Page
Then user will be able to see Albums
And year album was published
And the songs that are on those albums

# Technical Notes
create Music.html
add album covers 
Add years of the albums
add songs that belong in the albums

Close #10

**Comment by AmandaM04** [comment]
![band site - music pg](https://user-images.githubusercontent.com/36489047/37375103-296edf9a-26ec-11e8-989a-442e0ded128d.jpg)
